name: Check if container image is runnable, extract os-release
description: >
  Run container and extract /etc/os-release as JSON

inputs:
  name:
    description: Container image name
    required: true

outputs:
  os-release:
    description: Parsed /etc/os-release as JSON
    value: ${{ steps.os-release.outputs.json }}

runs:
  using: composite
  steps:

    - id: os-release
      shell: bash
      env:
        NAME: ${{ inputs.name }}
      run: |
        # Run container (no pull) and extract os-release

        source "$GITHUB_ACTION_PATH/../util"
        : "${NAME:?}"

        os_release=$(mktemp --tmpdir)
        podman run --pull=never "$NAME" cat /etc/os-release > "$os_release"

        >&2 tee -a "$GITHUB_OUTPUT" << EOF
        json=$(env_to_json "$os_release")
        EOF
